set number

set showmatch

set tabstop=4

set shiftwidth=4

set autoindent

set paste

set nocompatible

syntax on

set showmode

set showcmd

set encoding=utf-8

set t_Co=256

filetype indent on

set expandtab

set softtabstop=4

set textwidth=80

set wrap

set linebreak

set ruler

set hlsearch

set incsearch

set ignorecase

set wildmenu
set wildmode=longest:list,full
